name: Rom Poster Bot

on:
  push:
    paths-ignore:
      - '.github/scripts/file_ids.txt'
      - 'README.md'
  workflow_dispatch:
    inputs:
      repost:
        description: 'MD5 hash of the device you want to Re-Post'
        required: false
        type: string

env:
  GitHubMail: "mdst798@gmail.com"
  GitHubName: "Matrrixx-bot"
  GitHubToken: ${{ secrets.GH_TOKEN }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_IDS: ${{ secrets.CHAT_IDS }}
  REPOST_MD5: ${{ github.event.inputs.repost }}

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt remove python3-yaml
          sudo pip install pyTelegramBotAPI noobstuffs

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global color.ui true
          git config --global credential.helper store
          echo "https://${GitHubName}:${GitHubToken}@github.com" > ~/.git-credentials

      - name: Run RomPosterBot
        run: sudo -E python3 .github/scripts/post.py

      - name: Commit and Push Changes
        if: ${{ github.event.inputs.repost == null }}
        run: | 
          git fetch && git pull
          COMMIT_MESSAGE=$(cat commit_mesg.txt)
          rm commit_mesg.txt
          git add . && git commit -sm "$COMMIT_MESSAGE"
          git push origin
